### ISSUE TITLE
我想问一下我写校园疫情学生用户注册，这样写怎么不行，接口测试报错404

### ISSUE THREAD

**Issue by Therainbower** [Hongjilin/Campus-epidemic-prevention-and-control-syste#1]

**Comment by Hongjilin** [comment]
404是你路由都没进来，跟这里是没关系的

**Comment by Therainbower** [comment]
/**
 * 学生注册
 */
router.get('/LoginUp',function (req,res) {
    student.LoginUp(req,res)
})
路由是这样设置的，然后测试接口是http://localhost:3000/students/LoginUp，你看下这样是正确的吗。

**Comment by Therainbower** [comment]
> 404是你路由都没进来，跟这里是没关系的

那个，是不是路由的路径首字母不能是大写的。

**Comment by Therainbower** [comment]
还有一个问题我就是想问一下，发布公告和班级添加都会生成公告id或班级id，请问这两个id是怎么生成的，是系统自动生成的嘛。
